spring.application.name=ai-img-back
spring.datasource.url=jdbc:postgresql://localhost:5432/ai-img-back
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog-master.xml